baseURL = "https://rosswilliams.id.au/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Ross Williams' Profile Page"

# Menu config
[menu]
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About Me"
    url = "/about/"
    title = ""
    weight = 1

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "dark"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/gunzy83/rosswilliams.id.au"
  #  which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = "sha256"
  # website title for Open Graph and Twitter Cards
  title = "Ross Williams' Profile Page"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "Ross Williams' personal landing page."
  # website images for Open Graph and Twitter Cards
  images = ["/icon.png"]

# Author config
  [params.author]
    name = "Ross Williams"
    email = "me@rosswilliams.id.au"
    link = ""

  # Header config
  [params.header]
    #  Header title config
    [params.header.title]
      name = ""
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = '<i class="fas fa-cloud fa-fw"></i>'

  # Footer config
  [params.footer]
    # Site creation time
    since = 2021
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  #  App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "rosswilliams.id.au"
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = "/favicon.svg"
    # Android browser theme color
    themeColor = "#1f2937"
    # Safari mask icon color
    iconColor = "#60a5fa"
    # Windows v8-10 tile color
    tileColor = "#2b5797"

  # Home page config
  [params.home]
    # Home page profile
    [params.home.profile]
      # URL of avatar shown in home page
      avatarURL = "/avatar.png"
      #  title shown in home page (HTML format is supported)
      title = "Ross Williams"
      # subtitle shown in home page (HTML format is supported)
      subtitle = "Engineering Leader | AWS | DevOps | SRE | Linux | Security"
      # whether to use typeit animation for subtitle
      typeit = false
    # Home page posts
    [params.home.posts]
      enable = false

  # Social config about the author
  [params.social]
    GitHub = "gunzy83"
    Linkedin = "rosswilliams83"
    Twitter = "gunzy83"
    Keybase = "gunzy83"
    Email = "me@rosswilliams.id.au"
    RSS = false

  #  Analytics config
  [params.analytics]
    enable = false

  # Cookie consent config
  [params.cookieconsent]
    enable = true
    # text strings used for Cookie consent banner
    [params.cookieconsent.content]
      message = "This website uses Cookies to save your theme selection. Yep, that's it."
      dismiss = ""
      link = ""
