[build]
  command = "hugo"
  publish = "public"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ':(exclude)renovate.json' ':(exclude)README.md' ':(exclude)mise.toml' ':(exclude).prettierignore' ':(exclude).gitignore'"

[build.environment]
  HUGO_VERSION = "0.145.0"

[[headers]]
  # Headers for entire site
  for = "/*"
  [headers.values]
    # Content Security Policy (CSP) definition
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net/npm/clipboard@2.0.11/dist/clipboard.min.js https://cdn.jsdelivr.net/npm/lazysizes@5.3.2/lazysizes.min.js https://cdn.jsdelivr.net/npm/sharer.js@0.5.1/sharer.min.js https://cdn.jsdelivr.net/npm/cookieconsent@3.1.1/build/cookieconsent.min.js; style-src 'self' 'unsafe-hashes' 'sha256-dH+oOZOdDv+MWU0F8bCZOoFHX0jFM4+bwNqOKujbv90=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' https://cdn.jsdelivr.net; object-src 'none'; base-uri 'self'; connect-src 'self'; font-src 'self' https://cdn.jsdelivr.net; frame-src 'self' https://app.netlify.com; img-src 'self' https://cdn.jsdelivr.net; manifest-src 'self'; media-src 'self';"
    # Strict Transport Security (HSTS)
    Strict-Transport-Security = "max-age=63072000; includeSubdomains"
    # X-Content-Type-Options
    X-Content-Type-Options = "nosniff"
    # X-Frame-Options
    X-Frame-Options = "DENY"
    # X-XSS-Protection
    X-XSS-Protection = "1; mode=block"
    # Referrer-Policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Permissions-Policy
    Permissions-Policy = "interest-cohort=()"
